### ISSUE TITLE
betterproto v2.0.0b4

### ISSUE THREAD

**Issue by Liu-Weijie** [danielgtaylor/python-betterproto#401]
When I used the command as follow:
protoc -I . --python_betterproto_out=lib e2sm_rc.proto 
I got the error as follow:
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
My version of the protobuf compiler is 3.15
I don't know where it goes wrong?

**Comment by Gobot1234** [comment]
I can't tell from your issue, try using the latest version from GitHub.

**Comment by chitalian** [comment]
I am also hitting the same issue! @Liu-Weijie Can you please elaborate what you mean by `I found the version of the jinja2 is out of date, so I update it manually and it can work normally now`?

I ran 
`pip install jinja2 -U` and reran the command
```bash
python3 -m grpc_tools.protoc -I . --python_betterproto_out=. api.proto
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

With the same error

**Comment by aydarmynbay** [comment]
@chitalian try importing jinja2 in some other script. Don't know how, but it worked for me

**Comment by Liu-Weijie** [comment]
I am sorry that I just see the message.
you should pip uninstall jinja2 and pip install --upgrade jinja2
you can try it.

**Comment by chitalian** [comment]
@Gobot1234 
```protobuf
syntax = "proto3";

package sisu.v1.api;

message AnalysesResultRequest {
  int64 limit = 1;
  int64 starting_after = 2;
  int64 csv = 3;
  int64 top_drivers = 4;
}

```

**Comment by chitalian** [comment]
I just tried in a brand new docker container and it failed the same way

**Comment by Gobot1234** [comment]
What does `pip freeze` look like?

**Comment by chitalian** [comment]
```python
autopep8==1.6.0
betterproto==2.0.0b4
bleach==5.0.1
build==0.8.0
certifi==2022.6.15
charset-normalizer==2.1.0
commonmark==0.9.1
docutils==0.19
googleapis-common-protos==1.56.4
grpcio==1.47.0
grpcio-tools==1.47.0
grpclib==0.4.3rc3
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
idna==3.3
importlib-metadata==4.12.0
Jinja2==3.1.2
keyring==23.6.0
MarkupSafe==2.1.1
multidict==6.0.2
packaging==21.3
pep517==0.12.0
pkginfo==1.8.3
protobuf==3.20.1
pycodestyle==2.8.0
Pygments==2.12.0
pyparsing==3.0.9
-e git+ssh://git@github.com/sisudata/pysisu.git@43f742fb7922283e49be6406535511cad44de04e#egg=pysisu
python-dateutil==2.8.2
readme-renderer==35.0
requests==2.28.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
rich==12.4.4
six==1.16.0
toml==0.10.2
tomli==2.0.1
twine==4.0.1
urllib3==1.26.9
webencodings==0.5.1
zipp==3.8.0
```

**Comment by Gobot1234** [comment]
It looks to me like you didn't install "betterproto[compiler]", try `pip install -U "betterproto[compiler]" --pre`

**Comment by Gobot1234** [comment]
Seems like both of the issues here were fixed

**Comment by Gobot1234** [comment]
It should already be the latest version on master see #330

**Comment by chitalian** [comment]
This 
https://github.com/danielgtaylor/python-betterproto/pull/330
Doesnt fix it. 

On a new machine running 
`pip install -U "betterproto[compiler]" --pre`

yields this jinja version
```
ubuntu@ip-10-2-13-155:~/core/protos/public$ pip freeze | grep Jinja
Jinja2==2.11.3
```
https://github.com/danielgtaylor/python-betterproto/pull/402
This should fix it as well
